/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * admin_panel.java
 *
 * Created on Aug 28, 2015, 4:47:29 PM
 */
package aptitude_test_sys;
import java.awt.Image;
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class admin_panel extends javax.swing.JFrame {

DBConnect db=new DBConnect();
ResultSet rs;
PreparedStatement pst;
    public admin_panel() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
public boolean validate_login(String username,String password)
{
    try {
        pst=(PreparedStatement)db.c.prepareStatement("select * from admin where userName=? and password=?");
        pst.setString(1, username); 
        pst.setString(2, password);
        rs = pst.executeQuery();                        
        if(rs.next())            
           return true;    
        else
           return false;
   }
    
     catch (Exception e) {
        return false;
    }
}
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        lbl_login = new javax.swing.JLabel();
        lbl_exit = new javax.swing.JLabel();
        lbl_image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jPanel2.setPreferredSize(new java.awt.Dimension(440, 348));
        jPanel2.setLayout(null);

        username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        username.setBorder(null);
        username.setOpaque(false);
        jPanel2.add(username);
        username.setBounds(210, 120, 190, 20);

        password.setBorder(null);
        password.setOpaque(false);
        jPanel2.add(password);
        password.setBounds(220, 170, 180, 30);

        lbl_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aptitude_test_sys/images/Button.png"))); // NOI18N
        lbl_login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_loginMouseClicked(evt);
            }
        });
        jPanel2.add(lbl_login);
        lbl_login.setBounds(170, 250, 100, 40);

        lbl_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aptitude_test_sys/images/Bk.png"))); // NOI18N
        lbl_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_exitMouseClicked(evt);
            }
        });
        jPanel2.add(lbl_exit);
        lbl_exit.setBounds(310, 250, 40, 40);

        lbl_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aptitude_test_sys/images/copy_03.jpg"))); // NOI18N
        lbl_image.setPreferredSize(new java.awt.Dimension(440, 348));
        jPanel2.add(lbl_image);
        lbl_image.setBounds(-30, 0, 470, 348);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_loginMouseClicked
        // TODO add your handling code here:
        if(username.getText().length()==0)  // Checking for empty field
      JOptionPane.showMessageDialog(null, "Empty fields detected ! Please fill up all fields");
   else if(password.getPassword().length==0)  // Checking for empty field
      JOptionPane.showMessageDialog(null, "Empty fields detected ! Please fill up all fields");
   else{
       String user = username.getText();   // Collecting the input
       char[] pass = password.getPassword(); // Collecting the input
       String pwd = String.copyValueOf(pass);  // converting from array to string
       if(validate_login(user,pwd))
       {
           dashboard d=new dashboard();
           d.show();
           dispose();
       }
       else
          JOptionPane.showMessageDialog(null,"Invalid username or password");
   }

    }//GEN-LAST:event_lbl_loginMouseClicked

    private void lbl_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exitMouseClicked
        aptitude_test at = new aptitude_test();
        at.show();
        dispose();
    }//GEN-LAST:event_lbl_exitMouseClicked

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_exit;
    private javax.swing.JLabel lbl_image;
    private javax.swing.JLabel lbl_login;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
