/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * aptitude_test.java
 *
 * Created on Aug 28, 2015, 8:19:10 PM
 */
package aptitude_test_sys;


/**
 *
 * @author hp
 */
public class aptitude_test extends javax.swing.JFrame {

    /** Creates new form aptitude_test */
    public aptitude_test() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_admin = new javax.swing.JButton();
        btn_student = new javax.swing.JButton();
        lbl_exit = new javax.swing.JLabel();
        lbl_logo = new javax.swing.JLabel();
        lbl_image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 800, 600));
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(466, 331));
        jPanel1.setLayout(null);

        btn_admin.setBackground(new java.awt.Color(204, 204, 204));
        btn_admin.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_admin.setForeground(new java.awt.Color(255, 102, 0));
        btn_admin.setText("ADMIN");
        btn_admin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_adminActionPerformed(evt);
            }
        });
        jPanel1.add(btn_admin);
        btn_admin.setBounds(110, 160, 90, 30);

        btn_student.setBackground(new java.awt.Color(204, 204, 204));
        btn_student.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_student.setForeground(new java.awt.Color(255, 102, 0));
        btn_student.setText("STUDENT");
        btn_student.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_studentActionPerformed(evt);
            }
        });
        jPanel1.add(btn_student);
        btn_student.setBounds(260, 160, 100, 30);

        lbl_exit.setForeground(new java.awt.Color(255, 102, 0));
        lbl_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aptitude_test_sys/images/Exit1.png"))); // NOI18N
        lbl_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_exitMouseClicked(evt);
            }
        });
        jPanel1.add(lbl_exit);
        lbl_exit.setBounds(210, 260, 40, 40);

        lbl_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aptitude_test_sys/images/copy.png"))); // NOI18N
        jPanel1.add(lbl_logo);
        lbl_logo.setBounds(30, 30, 430, 100);

        lbl_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aptitude_test_sys/images/Copy_02.jpg"))); // NOI18N
        lbl_image.setMaximumSize(new java.awt.Dimension(466, 331));
        lbl_image.setMinimumSize(new java.awt.Dimension(466, 331));
        lbl_image.setPreferredSize(new java.awt.Dimension(466, 331));
        jPanel1.add(lbl_image);
        lbl_image.setBounds(0, 0, 466, 331);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exitMouseClicked
        dispose();
    }//GEN-LAST:event_lbl_exitMouseClicked

    private void btn_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adminActionPerformed
        admin_panel ap=new admin_panel();
        ap.show();
        dispose();
    }//GEN-LAST:event_btn_adminActionPerformed

    private void btn_studentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_studentActionPerformed
        student_registration st=new student_registration();
        st.show();
        dispose();
        
    }//GEN-LAST:event_btn_studentActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_admin;
    private javax.swing.JButton btn_student;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_exit;
    private javax.swing.JLabel lbl_image;
    private javax.swing.JLabel lbl_logo;
    // End of variables declaration//GEN-END:variables
}
