
package aptitude_test_sys;

public class MAIN extends javax.swing.JFrame {

    public MAIN() {
        initComponents();
        this.setLocationRelativeTo(null);
        new Thread()
        {
          public void run()
          {
              for(int i=0; i<101; i++)
              {
                  try 
                  {
                      sleep(50);
                      lbl_progress.setValue(i);
                      if(lbl_progress.getValue()==100)
                      {
                          dispose();
                      }
                  } 
                  catch (Exception e) 
                  {
                      
                  }
              }
              aptitude_test at=new aptitude_test();
              at.show();
          }
        }.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbl_progress = new javax.swing.JProgressBar();
        lbl_image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jPanel1.setMinimumSize(new java.awt.Dimension(1000, 503));
        jPanel1.setPreferredSize(new java.awt.Dimension(760, 503));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aptitude_test_sys/images/onlinelogomaker-061416-0302.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 140, 640, 190);

        lbl_progress.setForeground(new java.awt.Color(255, 102, 0));
        lbl_progress.setToolTipText("");
        lbl_progress.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        lbl_progress.setStringPainted(true);
        jPanel1.add(lbl_progress);
        lbl_progress.setBounds(270, 370, 240, 30);

        lbl_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aptitude_test_sys/images/bg2.jpg"))); // NOI18N
        lbl_image.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        jPanel1.add(lbl_image);
        lbl_image.setBounds(0, 0, 760, 503);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_image;
    private javax.swing.JProgressBar lbl_progress;
    // End of variables declaration//GEN-END:variables
}
