/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package aptitude_test_sys;
import javax.swing.JOptionPane;
import java.sql.*;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author hp
 */
public class question extends javax.swing.JFrame {
DBConnect db=new DBConnect();
ResultSet rs;
PreparedStatement pst;
    /**
     * Creates new form question
     */
    public question() {
        initComponents();
        this.setLocationRelativeTo(null);
        Fillcombo();
        FillTableAdd("select * from question");
        FillTableDel("select * from question");
        FillTableUpd("select * from question");
        
    }
 public void FillTableAdd(String sel)
{
    try
    {
    rs=db.s.executeQuery(sel);
    addTable.setModel(DbUtils.resultSetToTableModel(rs));
    }
    catch(Exception e)
    {
        JOptionPane.showMessageDialog(this, e);
    }
}
    public void FillTableDel(String sel)
{
    try
    {
    rs=db.s.executeQuery(sel);
    delTable.setModel(DbUtils.resultSetToTableModel(rs));
    }
    catch(Exception e)
    {
        JOptionPane.showMessageDialog(this, e);
    }
}
  public void FillTableUpd(String sel)
{
    try
    {
    rs=db.s.executeQuery(sel);
    updTable.setModel(DbUtils.resultSetToTableModel(rs));
    }
    catch(Exception e)
    {
        JOptionPane.showMessageDialog(this, e);
    }
}


public void Fillcombo()
      {
        try
        {
        String sel = "select * from subject";
        pst =  db.c.prepareStatement(sel);
        rs = pst.executeQuery();

          while(rs.next())
             {
             String subj = rs.getString("subject_name");
             addselect_subject.addItem(subj);
             updselect_subject.addItem(subj);
             }
        }
        catch(Exception e)
        {
        JOptionPane.showMessageDialog(null, "column not found");
        }
      }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        addoption1 = new javax.swing.JTextField();
        add_new = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        addTable = new javax.swing.JTable();
        AddQuestion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        addquestion_name = new javax.swing.JTextArea();
        AddOption_1 = new javax.swing.JLabel();
        AddOption_2 = new javax.swing.JLabel();
        addoption2 = new javax.swing.JTextField();
        addoption3 = new javax.swing.JTextField();
        AddOption_3 = new javax.swing.JLabel();
        AddOption_4 = new javax.swing.JLabel();
        addoption4 = new javax.swing.JTextField();
        addselect_subject = new javax.swing.JComboBox();
        AddAnswer = new javax.swing.JLabel();
        addanswer = new javax.swing.JTextField();
        AddSelect_Subject = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbl_logout = new javax.swing.JLabel();
        image_label = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        updoption1 = new javax.swing.JTextField();
        update = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        updTable = new javax.swing.JTable();
        updOption_1 = new javax.swing.JLabel();
        UpdOption_2 = new javax.swing.JLabel();
        updoption2 = new javax.swing.JTextField();
        updoption3 = new javax.swing.JTextField();
        UpdOption_3 = new javax.swing.JLabel();
        UpdOption_4 = new javax.swing.JLabel();
        updoption4 = new javax.swing.JTextField();
        updselect_subject = new javax.swing.JComboBox();
        Answer1 = new javax.swing.JLabel();
        updanswer = new javax.swing.JTextField();
        UpdSelect_Subject = new javax.swing.JLabel();
        UpdQuestion = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        updquestion_name = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        image_label1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        delete = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        delTable = new javax.swing.JTable();
        DelQuestion = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        delquestion_name = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        image_label2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTabbedPane1.setForeground(new java.awt.Color(102, 51, 0));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(457, 381));

        jPanel1.setLayout(null);

        addoption1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        addoption1.setForeground(new java.awt.Color(102, 51, 0));
        addoption1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addoption1ActionPerformed(evt);
            }
        });
        jPanel1.add(addoption1);
        addoption1.setBounds(140, 340, 100, 30);

        add_new.setBackground(new java.awt.Color(204, 204, 204));
        add_new.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        add_new.setForeground(new java.awt.Color(255, 102, 0));
        add_new.setText("Insert");
        add_new.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_newActionPerformed(evt);
            }
        });
        jPanel1.add(add_new);
        add_new.setBounds(140, 510, 100, 30);

        addTable.setBackground(new java.awt.Color(102, 102, 102));
        addTable.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        addTable.setForeground(new java.awt.Color(255, 255, 255));
        addTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Question_id", "Question_name", "Option_1", "Option_2", "Option_3", "Option_4", "Answer", "Subject_name"
            }
        ));
        addTable.setSelectionBackground(new java.awt.Color(255, 255, 255));
        addTable.setSelectionForeground(new java.awt.Color(102, 51, 0));
        jScrollPane4.setViewportView(addTable);

        jPanel1.add(jScrollPane4);
        jScrollPane4.setBounds(30, 90, 480, 90);

        AddQuestion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        AddQuestion.setForeground(new java.awt.Color(255, 255, 255));
        AddQuestion.setText("Question");
        jPanel1.add(AddQuestion);
        AddQuestion.setBounds(20, 230, 71, 23);

        addquestion_name.setColumns(20);
        addquestion_name.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        addquestion_name.setForeground(new java.awt.Color(102, 51, 0));
        addquestion_name.setRows(5);
        jScrollPane1.setViewportView(addquestion_name);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(120, 220, 310, 100);

        AddOption_1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        AddOption_1.setForeground(new java.awt.Color(255, 255, 255));
        AddOption_1.setText("  { A }");
        jPanel1.add(AddOption_1);
        AddOption_1.setBounds(60, 340, 50, 20);

        AddOption_2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        AddOption_2.setForeground(new java.awt.Color(255, 255, 255));
        AddOption_2.setText("  { B }");
        jPanel1.add(AddOption_2);
        AddOption_2.setBounds(310, 340, 50, 20);

        addoption2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        addoption2.setForeground(new java.awt.Color(102, 51, 0));
        addoption2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addoption2ActionPerformed(evt);
            }
        });
        jPanel1.add(addoption2);
        addoption2.setBounds(390, 340, 100, 30);

        addoption3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        addoption3.setForeground(new java.awt.Color(102, 51, 0));
        addoption3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addoption3ActionPerformed(evt);
            }
        });
        jPanel1.add(addoption3);
        addoption3.setBounds(140, 400, 100, 30);

        AddOption_3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        AddOption_3.setForeground(new java.awt.Color(255, 255, 255));
        AddOption_3.setText("  { C }");
        jPanel1.add(AddOption_3);
        AddOption_3.setBounds(60, 400, 60, 20);

        AddOption_4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        AddOption_4.setForeground(new java.awt.Color(255, 255, 255));
        AddOption_4.setText("  { D }");
        jPanel1.add(AddOption_4);
        AddOption_4.setBounds(310, 400, 50, 20);

        addoption4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        addoption4.setForeground(new java.awt.Color(102, 51, 0));
        jPanel1.add(addoption4);
        addoption4.setBounds(390, 400, 100, 30);

        addselect_subject.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        addselect_subject.setForeground(new java.awt.Color(102, 51, 0));
        addselect_subject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addselect_subjectActionPerformed(evt);
            }
        });
        jPanel1.add(addselect_subject);
        addselect_subject.setBounds(390, 460, 100, 30);

        AddAnswer.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        AddAnswer.setForeground(new java.awt.Color(255, 255, 255));
        AddAnswer.setText("Answer");
        jPanel1.add(AddAnswer);
        AddAnswer.setBounds(20, 460, 80, 20);

        addanswer.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        addanswer.setForeground(new java.awt.Color(102, 51, 0));
        jPanel1.add(addanswer);
        addanswer.setBounds(140, 460, 100, 30);

        AddSelect_Subject.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        AddSelect_Subject.setForeground(new java.awt.Color(255, 255, 255));
        AddSelect_Subject.setText("Subject");
        jPanel1.add(AddSelect_Subject);
        AddSelect_Subject.setBounds(300, 460, 50, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aptitude_test_sys/images/Bk.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1);
        jLabel1.setBounds(320, 510, 40, 35);

        lbl_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aptitude_test_sys/images/Logout.png"))); // NOI18N
        lbl_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_logoutMouseClicked(evt);
            }
        });
        jPanel1.add(lbl_logout);
        lbl_logout.setBounds(430, 0, 100, 40);

        image_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aptitude_test_sys/images/add QA.jpg"))); // NOI18N
        image_label.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(image_label);
        image_label.setBounds(0, 0, 540, 560);

        jTabbedPane1.addTab("INSERT", new javax.swing.ImageIcon(getClass().getResource("/aptitude_test_sys/images/Add.png")), jPanel1); // NOI18N

        jPanel2.setLayout(null);

        updoption1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        updoption1.setForeground(new java.awt.Color(102, 51, 0));
        updoption1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updoption1ActionPerformed(evt);
            }
        });
        jPanel2.add(updoption1);
        updoption1.setBounds(140, 340, 100, 30);

        update.setBackground(new java.awt.Color(204, 204, 204));
        update.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        update.setForeground(new java.awt.Color(255, 102, 0));
        update.setText("Update");
        update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel2.add(update);
        update.setBounds(140, 510, 90, 30);

        updTable.setBackground(new java.awt.Color(102, 102, 102));
        updTable.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        updTable.setForeground(new java.awt.Color(255, 255, 255));
        updTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Question_id", "Question_name", "Option_1", "Option_2", "Option_3", "Option_4", "Answer", "Subject_name"
            }
        ));
        updTable.setSelectionBackground(new java.awt.Color(255, 255, 255));
        updTable.setSelectionForeground(new java.awt.Color(102, 51, 0));
        updTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updTableMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(updTable);

        jPanel2.add(jScrollPane5);
        jScrollPane5.setBounds(30, 90, 480, 90);

        updOption_1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        updOption_1.setForeground(new java.awt.Color(255, 255, 255));
        updOption_1.setText("  { A }");
        jPanel2.add(updOption_1);
        updOption_1.setBounds(60, 340, 40, 20);

        UpdOption_2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        UpdOption_2.setForeground(new java.awt.Color(255, 255, 255));
        UpdOption_2.setText("  { B }");
        jPanel2.add(UpdOption_2);
        UpdOption_2.setBounds(310, 340, 50, 20);

        updoption2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        updoption2.setForeground(new java.awt.Color(102, 51, 0));
        updoption2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updoption2ActionPerformed(evt);
            }
        });
        jPanel2.add(updoption2);
        updoption2.setBounds(390, 340, 100, 30);

        updoption3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        updoption3.setForeground(new java.awt.Color(102, 51, 0));
        updoption3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updoption3ActionPerformed(evt);
            }
        });
        jPanel2.add(updoption3);
        updoption3.setBounds(140, 400, 100, 30);

        UpdOption_3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        UpdOption_3.setForeground(new java.awt.Color(255, 255, 255));
        UpdOption_3.setText("  { C }");
        jPanel2.add(UpdOption_3);
        UpdOption_3.setBounds(60, 400, 40, 20);

        UpdOption_4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        UpdOption_4.setForeground(new java.awt.Color(255, 255, 255));
        UpdOption_4.setText("  { D }");
        jPanel2.add(UpdOption_4);
        UpdOption_4.setBounds(310, 400, 50, 20);

        updoption4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        updoption4.setForeground(new java.awt.Color(102, 51, 0));
        jPanel2.add(updoption4);
        updoption4.setBounds(390, 400, 100, 30);

        updselect_subject.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        updselect_subject.setForeground(new java.awt.Color(102, 51, 0));
        updselect_subject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updselect_subjectActionPerformed(evt);
            }
        });
        jPanel2.add(updselect_subject);
        updselect_subject.setBounds(390, 460, 100, 30);

        Answer1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Answer1.setForeground(new java.awt.Color(255, 255, 255));
        Answer1.setText("Answer");
        jPanel2.add(Answer1);
        Answer1.setBounds(20, 460, 80, 20);

        updanswer.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        updanswer.setForeground(new java.awt.Color(102, 51, 0));
        jPanel2.add(updanswer);
        updanswer.setBounds(140, 460, 100, 30);

        UpdSelect_Subject.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        UpdSelect_Subject.setForeground(new java.awt.Color(255, 255, 255));
        UpdSelect_Subject.setText("Subject");
        jPanel2.add(UpdSelect_Subject);
        UpdSelect_Subject.setBounds(300, 460, 60, 20);

        UpdQuestion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        UpdQuestion.setForeground(new java.awt.Color(255, 255, 255));
        UpdQuestion.setText("Question");
        jPanel2.add(UpdQuestion);
        UpdQuestion.setBounds(20, 230, 71, 23);

        updquestion_name.setColumns(20);
        updquestion_name.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        updquestion_name.setForeground(new java.awt.Color(102, 51, 0));
        updquestion_name.setRows(5);
        jScrollPane2.setViewportView(updquestion_name);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(120, 220, 310, 100);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aptitude_test_sys/images/Bk.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jLabel3);
        jLabel3.setBounds(320, 510, 40, 35);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aptitude_test_sys/images/Logout.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jLabel4);
        jLabel4.setBounds(430, 0, 100, 40);

        image_label1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aptitude_test_sys/images/update QA.jpg"))); // NOI18N
        jPanel2.add(image_label1);
        image_label1.setBounds(0, 0, 540, 560);

        jTabbedPane1.addTab("UPDATE", new javax.swing.ImageIcon(getClass().getResource("/aptitude_test_sys/images/upbutton.png")), jPanel2); // NOI18N

        jPanel3.setLayout(null);

        delete.setBackground(new java.awt.Color(204, 204, 204));
        delete.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 102, 0));
        delete.setText("Delete");
        delete.setBorder(null);
        delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel3.add(delete);
        delete.setBounds(150, 460, 90, 30);

        delTable.setBackground(new java.awt.Color(102, 102, 102));
        delTable.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        delTable.setForeground(new java.awt.Color(255, 255, 255));
        delTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Question_id", "Question_name", "Option_1", "Option_2", "Option_3", "Option_4", "Answer", "Subject_name"
            }
        ));
        delTable.setSelectionBackground(new java.awt.Color(255, 255, 255));
        delTable.setSelectionForeground(new java.awt.Color(102, 51, 0));
        delTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delTableMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(delTable);

        jPanel3.add(jScrollPane6);
        jScrollPane6.setBounds(30, 110, 480, 120);

        DelQuestion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        DelQuestion.setForeground(new java.awt.Color(255, 255, 255));
        DelQuestion.setText("Question");
        jPanel3.add(DelQuestion);
        DelQuestion.setBounds(30, 310, 57, 17);

        delquestion_name.setColumns(20);
        delquestion_name.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        delquestion_name.setForeground(new java.awt.Color(102, 51, 0));
        delquestion_name.setRows(5);
        jScrollPane3.setViewportView(delquestion_name);

        jPanel3.add(jScrollPane3);
        jScrollPane3.setBounds(140, 290, 310, 100);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aptitude_test_sys/images/Bk.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel5);
        jLabel5.setBounds(330, 460, 40, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aptitude_test_sys/images/Logout.png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel6);
        jLabel6.setBounds(430, 0, 100, 40);

        image_label2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aptitude_test_sys/images/delete QA.jpg"))); // NOI18N
        jPanel3.add(image_label2);
        image_label2.setBounds(0, 0, 540, 560);

        jTabbedPane1.addTab("DELETE", new javax.swing.ImageIcon(getClass().getResource("/aptitude_test_sys/images/delbutton.png")), jPanel3); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_newActionPerformed
        // TODO add your handling code here:
                try 
                {
                    if(addquestion_name.getText().equals("")||addoption1.getText().equals("")||addoption2.getText().equals("")||addoption3.getText().equals("")||addoption4.getText().equals("")||addanswer.getText().equals(""))
                    {
                        JOptionPane.showMessageDialog(this, "please fill all the fields");
                    }
                    else{
                   int ins= db.s.executeUpdate("insert into question values('"+addquestion_name.getText() + "','"+addoption1.getText() + "','"+addoption2.getText() + "','"+addoption3.getText() + "','"+addoption4.getText() + "','"+addanswer.getText() + "','"+addselect_subject.getSelectedItem() + "')");
                   if(ins>0)
                   {
                    JOptionPane.showMessageDialog(this, "question add");
                    addquestion_name.setText("");
                    addoption1.setText("");
                    addoption2.setText("");
                    addoption3.setText("");
                    addoption4.setText("");
                    addanswer.setText("");
                    FillTableAdd("select * from question");
                    FillTableUpd("select * from question");
                    FillTableDel("select * from question");
                    
                   }
                    }
                } 
                catch (Exception e) 
                {
                    JOptionPane.showMessageDialog(this, "invalid");
                    addquestion_name.setText("");
                    addoption1.setText("");
                    addoption2.setText("");
                    addoption3.setText("");
                    addoption4.setText("");
                    addanswer.setText("");
                }
            
      
    }//GEN-LAST:event_add_newActionPerformed

    private void addoption1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addoption1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addoption1ActionPerformed

    private void addoption2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addoption2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addoption2ActionPerformed

    private void addoption3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addoption3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addoption3ActionPerformed

    private void addselect_subjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addselect_subjectActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_addselect_subjectActionPerformed

    private void updoption1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updoption1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updoption1ActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        try 
                {
                   int upd= db.s.executeUpdate("update question set q_name='"+updquestion_name.getText()+"',option_1='"+updoption1.getText()+"',option_2='"+updoption2.getText()+"',option_3='"+updoption3.getText()+"',option_4='"+updoption4.getText()+"',answer='"+updanswer.getText()+"',subject_name='"+updselect_subject.getSelectedItem()+"'where q_id='"+updTable.getValueAt(updTable.getSelectedRow(),0) +"'");
                   if(upd>0)
                   {
                    JOptionPane.showMessageDialog(this, "question updated");
                    updquestion_name.setText("");
                    updoption1.setText("");
                    updoption2.setText("");
                    updoption3.setText("");
                    updoption4.setText("");
                    updanswer.setText("");
                    FillTableAdd("select * from question");
                    FillTableUpd("select * from question");
                    FillTableDel("select * from question");
                    
                   }
                   else
                   {
                       JOptionPane.showMessageDialog(this, "not updated");
                       updquestion_name.setText("");
                    updoption1.setText("");
                    updoption2.setText("");
                    updoption3.setText("");
                    updoption4.setText("");
                    updanswer.setText("");
                   }
                } 
                catch (Exception e) 
                {
                    JOptionPane.showMessageDialog(this, e);
                }
    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        try 
                {
                   int del= db.s.executeUpdate("delete from question where q_name='"+delquestion_name.getText()+"'");
                   if(del>0)
                   {
                    JOptionPane.showMessageDialog(this, "question deleted");
                    delquestion_name.setText("");
                    FillTableAdd("select * from question");
                    FillTableUpd("select * from question");
                    FillTableDel("select * from question");
                    
                   }
                } 
                catch (Exception e) 
                {
                    JOptionPane.showMessageDialog(this, "not deleted");
                    delquestion_name.setText("");
                }
    }//GEN-LAST:event_deleteActionPerformed

    private void updoption2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updoption2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updoption2ActionPerformed

    private void updoption3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updoption3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updoption3ActionPerformed

    private void updselect_subjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updselect_subjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updselect_subjectActionPerformed

    private void delTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delTableMouseClicked
        // TODO add your handling code here:
            try 
    {
     String sel="select * from question";
     rs=db.s.executeQuery(sel);
     int row=delTable.getSelectedRow();
        if (delTable.getRowSelectionAllowed()) 
        {
            String m1=delTable.getValueAt(row, 1).toString();
            delquestion_name.setText(m1);
        }
    } 
    catch (Exception e) 
    {
     System.out.println(e.getMessage());   
    }
    }//GEN-LAST:event_delTableMouseClicked

    private void updTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updTableMouseClicked
        // TODO add your handling code here:
        try 
    {
        String sel="select * from question";
     rs=db.s.executeQuery(sel);
     int row=updTable.getSelectedRow();
        if (updTable.getRowSelectionAllowed()) 
        {
            String m1=updTable.getValueAt(row, 1).toString();
            updquestion_name.setText(m1);
            String m2=updTable.getValueAt(row, 2).toString();
            updoption1.setText(m2);
            String m3=updTable.getValueAt(row, 3).toString();
            updoption2.setText(m3);
            String m4=updTable.getValueAt(row, 4).toString();
            updoption3.setText(m4);
            String m5=updTable.getValueAt(row, 5).toString();
            updoption4.setText(m5);
            String m6=updTable.getValueAt(row, 6).toString();
            updanswer.setText(m6);
            String m7=updTable.getValueAt(row, 7).toString();
            updselect_subject.setSelectedItem(m7);
        }
        else
        {
            JOptionPane.showMessageDialog(this, "failed");
        }
    } 
    catch (Exception e) 
    {
     System.out.println(e.getMessage());   
    }
    }//GEN-LAST:event_updTableMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        
        dashboard d = new dashboard();
        d.show();
        dispose();
        
    }//GEN-LAST:event_jLabel1MouseClicked

    private void lbl_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_logoutMouseClicked
        // TODO add your handling code here:
        admin_panel ap = new admin_panel();
        ap.show();
        dispose();
        
    }//GEN-LAST:event_lbl_logoutMouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        
        
        
dashboard d = new dashboard();
        d.show();
        dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        
        admin_panel ap = new admin_panel();
        ap.show();
        dispose();

        
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddAnswer;
    private javax.swing.JLabel AddOption_1;
    private javax.swing.JLabel AddOption_2;
    private javax.swing.JLabel AddOption_3;
    private javax.swing.JLabel AddOption_4;
    private javax.swing.JLabel AddQuestion;
    private javax.swing.JLabel AddSelect_Subject;
    private javax.swing.JLabel Answer1;
    private javax.swing.JLabel DelQuestion;
    private javax.swing.JLabel UpdOption_2;
    private javax.swing.JLabel UpdOption_3;
    private javax.swing.JLabel UpdOption_4;
    private javax.swing.JLabel UpdQuestion;
    private javax.swing.JLabel UpdSelect_Subject;
    private javax.swing.JTable addTable;
    private javax.swing.JButton add_new;
    private javax.swing.JTextField addanswer;
    private javax.swing.JTextField addoption1;
    private javax.swing.JTextField addoption2;
    private javax.swing.JTextField addoption3;
    private javax.swing.JTextField addoption4;
    private javax.swing.JTextArea addquestion_name;
    private javax.swing.JComboBox addselect_subject;
    private javax.swing.JTable delTable;
    private javax.swing.JButton delete;
    private javax.swing.JTextArea delquestion_name;
    private javax.swing.JLabel image_label;
    private javax.swing.JLabel image_label1;
    private javax.swing.JLabel image_label2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbl_logout;
    private javax.swing.JLabel updOption_1;
    private javax.swing.JTable updTable;
    private javax.swing.JTextField updanswer;
    private javax.swing.JButton update;
    private javax.swing.JTextField updoption1;
    private javax.swing.JTextField updoption2;
    private javax.swing.JTextField updoption3;
    private javax.swing.JTextField updoption4;
    private javax.swing.JTextArea updquestion_name;
    private javax.swing.JComboBox updselect_subject;
    // End of variables declaration//GEN-END:variables
}
