/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * student_registration.java
 *
 * Created on Aug 28, 2015, 4:01:18 PM
 */
package aptitude_test_sys;

import java.sql.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class student_registration extends javax.swing.JFrame {
DBConnect db=new DBConnect();
    ResultSet rs,rs1;
    PreparedStatement pst;
    /** Creates new form student_registration */
    public student_registration() {
        initComponents();
          this.setLocationRelativeTo(null);
        Fillcombo();
        try {
            rs1=db.s.executeQuery("select convert(date,getdate()) as reg_date");
            if(rs1.next())
            {  
                String DATE=rs1.getString("reg_date");
                lbl_date.setText(DATE);
                lbl_date.setVisible(false);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }
        
      public void Fillcombo()
      {
        try
        {
            
            
        String sel = "select * from subject";
        pst =  db.c.prepareStatement(sel);
        rs = pst.executeQuery();

          while(rs.next())
             {
             String subj = rs.getString("subject_name");
             combo_subject.addItem(subj);
             }
        }
        catch(Exception e)
        {
        JOptionPane.showMessageDialog(null, "column not found");
        }
      }
      

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_name = new javax.swing.JTextField();
        lbl_age = new javax.swing.JTextField();
        lbl_phone = new javax.swing.JTextField();
        lbl_qualification = new javax.swing.JTextField();
        combo_subject = new javax.swing.JComboBox();
        btn_start = new javax.swing.JButton();
        lbl_exit = new javax.swing.JLabel();
        lbl_back = new javax.swing.JLabel();
        lbl_date = new javax.swing.JLabel();
        lbl_image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        lbl_name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lbl_name.setBorder(null);
        lbl_name.setOpaque(false);
        lbl_name.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                lbl_nameCaretUpdate(evt);
            }
        });
        lbl_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl_nameActionPerformed(evt);
            }
        });
        jPanel1.add(lbl_name);
        lbl_name.setBounds(170, 100, 210, 30);

        lbl_age.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lbl_age.setBorder(null);
        lbl_age.setOpaque(false);
        jPanel1.add(lbl_age);
        lbl_age.setBounds(170, 140, 100, 30);

        lbl_phone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lbl_phone.setBorder(null);
        lbl_phone.setOpaque(false);
        jPanel1.add(lbl_phone);
        lbl_phone.setBounds(170, 180, 210, 21);

        lbl_qualification.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lbl_qualification.setBorder(null);
        lbl_qualification.setOpaque(false);
        jPanel1.add(lbl_qualification);
        lbl_qualification.setBounds(170, 210, 210, 30);

        combo_subject.setBorder(null);
        combo_subject.setOpaque(false);
        combo_subject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_subjectActionPerformed(evt);
            }
        });
        jPanel1.add(combo_subject);
        combo_subject.setBounds(170, 260, 100, 20);

        btn_start.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aptitude_test_sys/images/Start.png"))); // NOI18N
        btn_start.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_startActionPerformed(evt);
            }
        });
        jPanel1.add(btn_start);
        btn_start.setBounds(320, 318, 70, 20);

        lbl_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aptitude_test_sys/images/Exit1.png"))); // NOI18N
        lbl_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_exitMouseClicked(evt);
            }
        });
        jPanel1.add(lbl_exit);
        lbl_exit.setBounds(190, 340, 40, 40);

        lbl_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aptitude_test_sys/images/Bk.png"))); // NOI18N
        lbl_back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_backMouseClicked(evt);
            }
        });
        jPanel1.add(lbl_back);
        lbl_back.setBounds(60, 310, 40, 40);
        jPanel1.add(lbl_date);
        lbl_date.setBounds(340, 250, 70, 20);

        lbl_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aptitude_test_sys/images/REGISTERATION.jpg"))); // NOI18N
        jPanel1.add(lbl_image);
        lbl_image.setBounds(0, 0, 457, 381);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl_nameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_lbl_nameActionPerformed

    private void combo_subjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_subjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_subjectActionPerformed

    private void btn_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_startActionPerformed
        try 
        {
            String a,b,c,d,e,f,g,h;
            a="[A-Za-z\\s]{3,30}";
            b=lbl_name.getText();
            c="[0-9]{1,2}";
            d=lbl_age.getText();
            e="[0-9]{8,11}";
            f=lbl_phone.getText();
            g="[A-Za-z0-9]{3,30}";
            h=lbl_qualification.getText();
        Pattern p= Pattern.compile(a);
        Matcher m=p.matcher(b);
        Pattern p1= Pattern.compile(c);
        Matcher m1=p1.matcher(d);
        Pattern p2= Pattern.compile(e);
        Matcher m2=p2.matcher(f);
        Pattern p3= Pattern.compile(g);
        Matcher m3=p3.matcher(h);
                if(m.matches() && m1.matches() && m2.matches() && m3.matches())
                {
                int ins=db.s.executeUpdate("insert into register values('"+lbl_name.getText()+"','"+lbl_age.getText()+"','"+lbl_phone.getText()+"','"+lbl_qualification.getText()+"','"+combo_subject.getSelectedItem()+"','"+lbl_date.getText()+"')");
                if(ins>0)
                {
                  test t=new test(lbl_name.getText(),lbl_age.getText(),lbl_phone.getText(),lbl_qualification.getText(),(String)combo_subject.getSelectedItem(),lbl_date.getText());
                  t.show();
                  dispose();
                }
                }
                else
                {
                    if(lbl_name.getText().equals("") || lbl_age.getText().equals("") || lbl_phone.getText().equals("") || lbl_qualification.getText().equals(""))
                    {
                        JOptionPane.showMessageDialog(this, "Please fill all the field");
                    }
                    else if(!m.matches())
                    {
                        JOptionPane.showMessageDialog(this, "Minimum Three characters reqired for Student name");
                    }
                    else if(!m1.matches())
                    {
                      JOptionPane.showMessageDialog(this, "Minimum One number reqired for Student age");
                    }
                    else if(!m2.matches())
                    {
                        JOptionPane.showMessageDialog(this, "enter valid Phone no");
                    }
                    else if(!m3.matches())
                    {
                        JOptionPane.showMessageDialog(this, "Minimum Three characters reqired for Last Qualification");
                    }
                }
        } 
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(this, e);
        }
        
    }//GEN-LAST:event_btn_startActionPerformed

    private void lbl_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exitMouseClicked
        dispose();
    }//GEN-LAST:event_lbl_exitMouseClicked

    private void lbl_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_backMouseClicked
        aptitude_test at=new aptitude_test();
        at.show();
        dispose();
    }//GEN-LAST:event_lbl_backMouseClicked

    private void lbl_nameCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_lbl_nameCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_nameCaretUpdate

    /**
     * @param args the command line arguments
     */
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_start;
    private javax.swing.JComboBox combo_subject;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lbl_age;
    private javax.swing.JLabel lbl_back;
    private javax.swing.JLabel lbl_date;
    private javax.swing.JLabel lbl_exit;
    private javax.swing.JLabel lbl_image;
    private javax.swing.JTextField lbl_name;
    private javax.swing.JTextField lbl_phone;
    private javax.swing.JTextField lbl_qualification;
    // End of variables declaration//GEN-END:variables
}
