/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package aptitude_test_sys;

import java.io.PrintWriter;
import java.sql.*;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author hp
 */
public class subject extends javax.swing.JFrame {

    DBConnect db=new DBConnect();
    ResultSet rs;
    PreparedStatement pst;
    
    public subject() {
        initComponents();
        this.setLocationRelativeTo(null);
        FillTable("select * from subject");
    }

public boolean connect(String sub_name)
  {
    try 
    {
        pst=(PreparedStatement)db.c.prepareStatement("select * from subject where subject_name=?");
        pst.setString(1, sub_name);
        rs = pst.executeQuery(); 
        if(rs.next())            
             return true;
        else
             return false;
}
    catch(Exception e)
    {
        return false;
    }
  }

public void FillTable(String sel)
{
    try
    {
    rs=db.s.executeQuery(sel);
    tbl_subject.setModel(DbUtils.resultSetToTableModel(rs));
    }
    catch(Exception e)
    {
        JOptionPane.showMessageDialog(this, e);
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        subject_pane = new javax.swing.JScrollPane();
        tbl_subject = new javax.swing.JTable();
        lbl_subject_name = new javax.swing.JTextField();
        btn_add = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        lbl_logout = new javax.swing.JLabel();
        lbl_back = new javax.swing.JLabel();
        lbl_image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel4.setLayout(null);

        tbl_subject.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tbl_subject.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Topic ID", "Topic Name"
            }
        ));
        tbl_subject.setOpaque(false);
        tbl_subject.setSelectionBackground(new java.awt.Color(191, 152, 239));
        tbl_subject.setSelectionForeground(new java.awt.Color(122, 122, 122));
        tbl_subject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_subjectMouseClicked(evt);
            }
        });
        subject_pane.setViewportView(tbl_subject);

        jPanel4.add(subject_pane);
        subject_pane.setBounds(40, 90, 360, 100);

        lbl_subject_name.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbl_subject_name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel4.add(lbl_subject_name);
        lbl_subject_name.setBounds(170, 240, 90, 21);

        btn_add.setBackground(new java.awt.Color(204, 204, 204));
        btn_add.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_add.setForeground(new java.awt.Color(255, 102, 0));
        btn_add.setText("Add");
        btn_add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });
        jPanel4.add(btn_add);
        btn_add.setBounds(120, 280, 80, 25);

        btn_delete.setBackground(new java.awt.Color(204, 204, 204));
        btn_delete.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_delete.setForeground(new java.awt.Color(255, 102, 0));
        btn_delete.setText("Delete");
        btn_delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        jPanel4.add(btn_delete);
        btn_delete.setBounds(230, 280, 80, 25);

        lbl_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aptitude_test_sys/images/Logout.png"))); // NOI18N
        lbl_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_logoutMouseClicked(evt);
            }
        });
        jPanel4.add(lbl_logout);
        lbl_logout.setBounds(170, 350, 100, 35);

        lbl_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aptitude_test_sys/images/Bk.png"))); // NOI18N
        lbl_back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_backMouseClicked(evt);
            }
        });
        jPanel4.add(lbl_back);
        lbl_back.setBounds(50, 350, 40, 35);

        lbl_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aptitude_test_sys/images/add & delete.jpg"))); // NOI18N
        jPanel4.add(lbl_image);
        lbl_image.setBounds(0, 0, 450, 390);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_logoutMouseClicked
        
        admin_panel ap=new admin_panel();
        ap.show();
        dispose();
        
    }//GEN-LAST:event_lbl_logoutMouseClicked

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
       
        if (lbl_subject_name.getText().length() == 0) // Checking for empty field
        {
            JOptionPane.showMessageDialog(this, "Empty fields detected ! Please fill the field");
        } else {
            String sub_name = lbl_subject_name.getText();   // Collecting the input
            if (connect(sub_name)) {
                JOptionPane.showMessageDialog(this, "this is already a subject");
                lbl_subject_name.setText("");
            } else {
                try {
                   int ins= db.s.executeUpdate("insert into subject values('" + lbl_subject_name.getText() + "')");
                   if(ins>0)
                   {
                    JOptionPane.showMessageDialog(this, "insert successfully");
                    lbl_subject_name.setText("");
                    FillTable("select * from subject");
                   }
                   
                    else
                    {
                        JOptionPane.showMessageDialog(this, "invalid");
                        lbl_subject_name.setText("");
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, e);
                }
            }
        }
        
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        
        try 
        {
           int r=db.s.executeUpdate("delete from subject where subject_name='"+lbl_subject_name.getText()+"'");
            if(r>0)
            {
            JOptionPane.showMessageDialog(this, "delete successfully");
            FillTable("select * from subject");
            }
            else
            {
                JOptionPane.showMessageDialog(this,"fale");
            }
        } 
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(this, e);
            
        }
        
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void lbl_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_backMouseClicked
        
        dashboard d=new dashboard();
        d.show();
        dispose();
        
    }//GEN-LAST:event_lbl_backMouseClicked

    private void tbl_subjectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_subjectMouseClicked
        
        try 
    {
     String sel="select * from question";
     rs=db.s.executeQuery(sel);
     int row=tbl_subject.getSelectedRow();
        if (tbl_subject.getRowSelectionAllowed()) 
        {
            String m1=tbl_subject.getValueAt(row, 1).toString();
            lbl_subject_name.setText(m1);
        }
    } 
    catch (Exception e) 
    {
     System.out.println(e.getMessage());   
    }
        
    }//GEN-LAST:event_tbl_subjectMouseClicked

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_delete;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lbl_back;
    private javax.swing.JLabel lbl_image;
    private javax.swing.JLabel lbl_logout;
    private javax.swing.JTextField lbl_subject_name;
    private javax.swing.JScrollPane subject_pane;
    private javax.swing.JTable tbl_subject;
    // End of variables declaration//GEN-END:variables
}
